@url = http://localhost:3003/api/blogs
@invalidId = 3
@validId = 63c16f40b154fdd06ebee616
@ownerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imppa29uZW4iLCJpZCI6IjYzYzE1MzE5OGE1MjE1Y2RlMGJlYjUwNSIsImlhdCI6MTY3MzYyNDE3MCwiZXhwIjoxNjczNjI3NzcwfQ.-RFlPLphl8Bzz4EVDQQDsQS2F0bYFnHZf7pTnK2_aXE
@otherToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhbmtrYSIsImlkIjoiNjNjMTNhYTdhZDZjY2I3Mzg1ZGJlNDYxIiwiaWF0IjoxNjczNjI0NzQwLCJleHAiOjE2NzM2MjgzNDB9.nnQVMiewH1xQkSbs3tHUw8Zg7OT-dALEU0CjNni6vS4

DELETE {{url}}/{{invalidId}} HTTP/1.1

###

DELETE {{url}}/{{invalidId}} HTTP/1.1
Authorization: bearer {{ownerToken}}

###

DELETE {{url}}/{{validId}} HTTP/1.1

###

DELETE {{url}}/{{validId}} HTTP/1.1
Authorization: bearer {{ownerToken}}

###

DELETE {{url}}/{{validId}} HTTP/1.1
Authorization: bearer {{otherToken}}
