@url = http://localhost:3003/api/blogs
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imppa29uZW4iLCJpZCI6IjYzYzE4YmI4NTBjOWI4MTA0Nzg2MWE5NCIsImlhdCI6MTY3MzYyODYyOSwiZXhwIjoxNjczNjMyMjI5fQ.lLfjhfZu6uHQNHGdAs2d0tmoV8pDwcaxulXZKfQrpbQ

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "Ojasta allikkoon",
    "author": "Aku Ankka",
    "url": "http://www.ankanpulinat.pom",
    "likes": "5"
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "Neliapilasta kultalusikkaan",
    "author": "Hannu Hanhi",
    "url": "http://www.onnenpoika.pom",
    "likes": "27"
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "Raha ei kasva puissa",
    "author": "R. Ankka",
    "url": "http://www.saiturinporssi.pom",
    "likes": "1"
}
