@url = http://localhost:3003/api/blogs

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imppa29uZW4iLCJpZCI6IjYzYzE1MzE5OGE1MjE1Y2RlMGJlYjUwNSIsImlhdCI6MTY3MzYxNTM1OSwiZXhwIjoxNjczNjE4OTU5fQ.3Wuuo7vlxD5ZHHsZdlC-tUWywPLo5AuJUqJBKFf1_Gw

{
    "title": "Ojasta allikkoon",
    "author": "Aku Ankka",
    "url": "http://www.ankanpulinat.pom",
    "likes": "5"
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imppa29uZW4iLCJpZCI6IjYzYzE1MzE5OGE1MjE1Y2RlMGJlYjUwNSIsImlhdCI6MTY3MzYxNTM1OSwiZXhwIjoxNjczNjE4OTU5fQ.3Wuuo7vlxD5ZHHsZdlC-tUWywPLo5AuJUqJBKFf1_

{
    "title": "Neliapilasta kultalusikkaan",
    "author": "Hannu Hanhi",
    "url": "http://www.onnenpoika.pom",
    "likes": "27"
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "title": "Raha ei kasva puissa",
    "author": "R. Ankka",
    "url": "http://www.saiturinporssi.pom",
    "likes": "1"
}
